// This file is auto-generated by @hey-api/openapi-ts

export const accessProfileSchema = {
  type: "object",
  required: ["id", "name", "description", "assignedUserCount"],
  properties: {
    assignedUserCount: {
      type: "integer",
    },
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const accessProfileDetailsSchema = {
  type: "object",
  required: ["description", "id", "name"],
  properties: {
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    permittedSources: {
      $ref: "#/definitions/permittedSources",
    },
  },
} as const;

export const accessProfileInputSchema = {
  type: "object",
  required: ["description", "name", "permittedSources"],
  properties: {
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
    permittedSources: {
      $ref: "#/definitions/permittedSources",
    },
  },
} as const;

export const accessProfilesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessProfile",
  },
} as const;

export const accessReviewSchema = {
  type: "object",
  required: [
    "assigneeEmail",
    "assigneeName",
    "assignmentQuestion",
    "campaignId",
    "campaignName",
    "columnGroups",
    "createdAt",
    "creatorEmail",
    "draft",
    "dueDate",
    "relationshipChanges",
    "relationships",
    "rowGroups",
    "rowQuestion",
    "rowRemovals",
    "submittedAt",
  ],
  properties: {
    assigneeEmail: {
      type: "string",
    },
    assigneeName: {
      type: "string",
    },
    assignmentQuestion: {
      type: "string",
    },
    campaignId: {
      type: "integer",
    },
    campaignName: {
      type: "string",
    },
    columnGroups: {
      $ref: "#/definitions/accessReviewHeaderGroups",
    },
    createdAt: {
      $ref: "#/definitions/date",
    },
    creatorEmail: {
      type: "string",
    },
    draft: {
      type: "boolean",
    },
    dueDate: {
      $ref: "#/definitions/date",
    },
    relationshipChanges: {
      $ref: "#/definitions/accessReviewRelationshipChanges",
    },
    relationships: {
      $ref: "#/definitions/accessReviewRelationships",
    },
    rowGroups: {
      $ref: "#/definitions/accessReviewHeaderGroups",
    },
    rowQuestion: {
      type: "string",
    },
    rowRemovals: {
      $ref: "#/definitions/accessReviewRowRemovals",
    },
    submissionComment: {
      type: "string",
      "x-nullable": true,
    },
    submittedAt: {
      $ref: "#/definitions/dateTime",
    },
  },
} as const;

export const accessReviewAttributeTypeSchema = {
  type: "object",
  required: ["attributeTypeId", "attributeTypeName"],
  properties: {
    attributeTypeId: {
      type: "string",
    },
    attributeTypeName: {
      type: "string",
    },
  },
} as const;

export const accessReviewAttributeTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewAttributeType",
  },
} as const;

export const accessReviewFormSchema = {
  type: "object",
  required: [
    "assigneeName",
    "assignmentQuestion",
    "campaignName",
    "columnGroups",
    "createdAt",
    "dueDate",
    "relationships",
    "rowGroups",
    "rowQuestion",
    "submitted",
    "toolbarBackgroundColor",
    "welcomeScreenHtml",
  ],
  properties: {
    assigneeName: {
      type: "string",
    },
    assignmentQuestion: {
      type: "string",
    },
    campaignName: {
      type: "string",
    },
    columnGroups: {
      $ref: "#/definitions/accessReviewHeaderGroups",
    },
    relationships: {
      $ref: "#/definitions/accessReviewRelationships",
    },
    rowGroups: {
      $ref: "#/definitions/accessReviewHeaderGroups",
    },
    rowQuestion: {
      type: "string",
    },
    submitted: {
      type: "boolean",
    },
    toolbarBackgroundColor: {
      type: "string",
    },
    welcomeScreenHtml: {
      type: "string",
    },
  },
} as const;

export const accessReviewHeaderSchema = {
  type: "object",
  required: ["attributeAssignments", "entityId", "entityName", "id"],
  properties: {
    attributeAssignments: {
      $ref: "#/definitions/attributeAssignments",
    },
    entityId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
    id: {
      type: "integer",
    },
  },
} as const;

export const accessReviewHeaderGroupSchema = {
  type: "object",
  required: [
    "attributeTypes",
    "entityTypeId",
    "entityTypePlural",
    "entityTypeSingular",
    "headers",
    "sourceId",
    "sourceName",
  ],
  properties: {
    attributeTypes: {
      $ref: "#/definitions/accessReviewAttributeTypes",
    },
    defaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    entityTypeId: {
      type: "string",
    },
    entityTypePlural: {
      type: "string",
    },
    entityTypeSingular: {
      type: "string",
    },
    headers: {
      $ref: "#/definitions/accessReviewHeaders",
    },
    sourceId: {
      type: "integer",
    },
    sourceName: {
      type: "string",
    },
  },
} as const;

export const accessReviewHeaderGroupsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewHeaderGroup",
  },
} as const;

export const accessReviewHeaderOptionSchema = {
  type: "object",
  required: ["entityId", "entityName", "label", "links"],
  properties: {
    entityId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
    label: {
      type: "string",
    },
    links: {
      $ref: "#/definitions/accessReviewHeaderOptionLinks",
    },
  },
} as const;

export const accessReviewHeaderOptionLinkSchema = {
  type: "object",
  required: ["entityId", "entityTypeId", "sourceId"],
  properties: {
    entityId: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewHeaderOptionLinksSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewHeaderOptionLink",
  },
} as const;

export const accessReviewHeaderOptionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewHeaderOption",
  },
} as const;

export const accessReviewHeadersSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewHeader",
  },
} as const;

export const accessReviewInputSchema = {
  type: "object",
  required: [
    "assigneeEmail",
    "assigneeName",
    "assignmentQuestion",
    "campaignId",
    "columnGroups",
    "draft",
    "relationships",
    "rowGroups",
    "rowQuestion",
  ],
  properties: {
    assigneeEmail: {
      type: "string",
      format: "email",
    },
    assigneeName: {
      type: "string",
    },
    assignmentQuestion: {
      type: "string",
    },
    campaignId: {
      type: "integer",
    },
    columnGroups: {
      $ref: "#/definitions/accessReviewInputHeaderGroups",
    },
    draft: {
      type: "boolean",
    },
    relationships: {
      $ref: "#/definitions/accessReviewInputRelationships",
    },
    rowGroups: {
      $ref: "#/definitions/accessReviewInputHeaderGroups",
    },
    rowQuestion: {
      type: "string",
    },
  },
} as const;

export const accessReviewInputHeaderSchema = {
  type: "object",
  required: ["entityExternalId", "entityName"],
  properties: {
    entityExternalId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
  },
} as const;

export const accessReviewInputHeaderGroupSchema = {
  type: "object",
  required: ["entityTypeId", "headers", "sourceId"],
  properties: {
    defaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    entityTypeId: {
      type: "string",
    },
    headers: {
      $ref: "#/definitions/accessReviewInputHeaders",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewInputHeaderGroupsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewInputHeaderGroup",
  },
} as const;

export const accessReviewInputHeadersSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewInputHeader",
  },
} as const;

export const accessReviewInputRelationshipSchema = {
  type: "object",
  required: [
    "columnEntityId",
    "columnEntityTypeExternalId",
    "columnSourceId",
    "rowEntityId",
    "rowEntityTypeExternalId",
    "rowSourceId",
  ],
  properties: {
    columnEntityId: {
      type: "string",
    },
    columnEntityTypeExternalId: {
      type: "string",
    },
    columnSourceId: {
      type: "integer",
    },
    rowEntityId: {
      type: "string",
    },
    rowEntityTypeExternalId: {
      type: "string",
    },
    rowSourceId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewInputRelationshipsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewInputRelationship",
  },
} as const;

export const accessReviewReferenceSchema = {
  type: "object",
  required: ["id", "requestLink"],
  properties: {
    id: {
      type: "integer",
    },
    requestLink: {
      type: "string",
    },
  },
} as const;

export const accessReviewRelationshipSchema = {
  type: "object",
  required: ["columnEntityId", "columnId", "rowEntityId", "rowId"],
  properties: {
    columnEntityId: {
      type: "string",
    },
    columnId: {
      type: "integer",
    },
    rowEntityId: {
      type: "string",
    },
    rowId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewRelationshipChangeSchema = {
  type: "object",
  required: ["columnId", "comment", "id", "rowId", "status"],
  properties: {
    columnId: {
      type: "integer",
    },
    comment: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    rowId: {
      type: "integer",
    },
    status: {
      $ref: "#/definitions/changeRequestStatus",
    },
  },
} as const;

export const accessReviewRelationshipChangesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewRelationshipChange",
  },
} as const;

export const accessReviewRelationshipsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewRelationship",
  },
} as const;

export const accessReviewReminderSchema = {
  type: "object",
  required: ["id", "periodDays", "repeated"],
  properties: {
    id: {
      type: "integer",
    },
    periodDays: {
      type: "integer",
    },
    repeated: {
      type: "boolean",
    },
  },
} as const;

export const accessReviewReminderInputSchema = {
  type: "object",
  required: ["beforeDueDate", "periodDays", "repeated"],
  properties: {
    beforeDueDate: {
      type: "boolean",
    },
    periodDays: {
      $ref: "#/definitions/positiveInteger",
    },
    repeated: {
      type: "boolean",
    },
  },
} as const;

export const accessReviewRemindersSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewReminder",
  },
} as const;

export const accessReviewRowRemovalSchema = {
  type: "object",
  required: ["comment", "id", "rowId", "status"],
  properties: {
    comment: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    rowId: {
      type: "integer",
    },
    status: {
      $ref: "#/definitions/changeRequestStatus",
    },
  },
} as const;

export const accessReviewRowRemovalsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewRowRemoval",
  },
} as const;

export const accessReviewSubmissionSchema = {
  type: "object",
  required: ["comment", "relationshipChanges", "rowRemovals", "token"],
  properties: {
    comment: {
      type: "string",
    },
    relationshipChanges: {
      $ref: "#/definitions/accessReviewSubmissionRelationshipChanges",
    },
    rowRemovals: {
      $ref: "#/definitions/accessReviewSubmissionRowRemovals",
    },
    token: {
      type: "string",
    },
  },
} as const;

export const accessReviewSubmissionRelationshipChangeSchema = {
  type: "object",
  required: ["columnId", "comment", "rowId"],
  properties: {
    columnId: {
      type: "integer",
    },
    comment: {
      type: "string",
    },
    rowId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewSubmissionRelationshipChangesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewSubmissionRelationshipChange",
  },
} as const;

export const accessReviewSubmissionRowRemovalSchema = {
  type: "object",
  required: ["comment", "rowId"],
  properties: {
    comment: {
      type: "string",
    },
    rowId: {
      type: "integer",
    },
  },
} as const;

export const accessReviewSubmissionRowRemovalsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/accessReviewSubmissionRowRemoval",
  },
} as const;

export const apiTokenSchema = {
  type: "object",
  required: ["createdAt", "description", "id", "name"],
  properties: {
    createdAt: {
      $ref: "#/definitions/dateTime",
    },
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    lastUsedAt: {
      $ref: "#/definitions/optionalDateTime",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const apiTokenInputSchema = {
  type: "object",
  required: ["description", "name"],
  properties: {
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const apiTokenSummarySchema = {
  type: "object",
  required: ["id", "secret"],
  properties: {
    id: {
      type: "integer",
    },
    secret: {
      type: "string",
    },
  },
} as const;

export const apiTokensSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/apiToken",
  },
} as const;

export const attributeAssignmentSchema = {
  type: "object",
  required: ["attributeTypeId", "value"],
  properties: {
    attributeTypeId: {
      type: "string",
    },
    value: {
      $ref: "#/definitions/attributeAssignmentValue",
    },
  },
} as const;

export const attributeAssignmentChangeRequestSchema = {
  type: "object",
  required: [
    "attributeTypeId",
    "attributeTypeName",
    "comment",
    "entityName",
    "entityId",
    "entityTypeId",
    "entityTypeSingular",
    "id",
    "requestedAt",
    "requestedBy",
    "sourceId",
    "sourceName",
    "status",
  ],
  properties: {
    attributeTypeId: {
      type: "string",
    },
    attributeTypeName: {
      type: "string",
    },
    comment: {
      type: "string",
    },
    correctedValue: {
      $ref: "#/definitions/attributeAssignmentValue",
    },
    entityId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    entityTypeSingular: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    requestedAt: {
      $ref: "#/definitions/dateTime",
    },
    requestedBy: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
    sourceName: {
      type: "string",
    },
    status: {
      $ref: "#/definitions/changeRequestStatus",
    },
  },
} as const;

export const attributeAssignmentChangeRequestInputSchema = {
  type: "object",
  required: [
    "attributeTypeId",
    "comment",
    "entityId",
    "entityTypeId",
    "sourceId",
  ],
  properties: {
    attributeTypeId: {
      type: "string",
    },
    booleanCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
    comment: {
      type: "string",
    },
    dateCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
    dateTimeCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
    entityId: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    numberCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
    sourceId: {
      type: "integer",
    },
    stringCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
    timeCorrectedValue: {
      type: "string",
      "x-nullable": true,
    },
  },
} as const;

export const attributeAssignmentChangeRequestPageSchema = {
  type: "object",
  required: ["items", "totalCount"],
  properties: {
    items: {
      $ref: "#/definitions/attributeAssignmentChangeRequests",
    },
    totalCount: {
      type: "integer",
    },
  },
} as const;

export const attributeAssignmentChangeRequestsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/attributeAssignmentChangeRequest",
  },
} as const;

export const attributeAssignmentValueSchema = {
  required: ["bool", "dateTime", "date", "number", "string", "time", "type"],
  properties: {
    bool: {
      type: "boolean",
    },
    date: {
      $ref: "#/definitions/date",
    },
    dateTime: {
      $ref: "#/definitions/dateTime",
    },
    number: {
      type: "number",
    },
    string: {
      type: "string",
    },
    time: {
      $ref: "#/definitions/time",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const attributeAssignmentsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/attributeAssignment",
  },
} as const;

export const attributeTypeSchema = {
  type: "object",
  required: ["archived", "description", "entityTypeId", "id", "name", "type"],
  properties: {
    archived: {
      type: "boolean",
    },
    description: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const attributeTypeInputSchema = {
  type: "object",
  required: ["description", "entityTypeId", "id", "name", "type"],
  properties: {
    description: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const attributeTypeInputsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/attributeTypeInput",
  },
} as const;

export const attributeTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/attributeType",
  },
} as const;

export const authModeSchema = {
  type: "string",
  enum: ["oidc", "password"],
} as const;

export const badRequestResponseSchema = {
  type: "object",
  required: ["errorMessage"],
  properties: {
    errorMessage: {
      type: "string",
    },
  },
} as const;

export const builtInConnectorOptionSchema = {
  type: "object",
  required: [
    "categories",
    "configKeys",
    "description",
    "helpUrl",
    "id",
    "longDescription",
    "name",
    "querySummaries",
    "schedulable",
  ],
  properties: {
    categories: {
      $ref: "#/definitions/strings",
    },
    configKeys: {
      $ref: "#/definitions/configKeys",
    },
    description: {
      type: "string",
    },
    helpUrl: {
      type: "string",
    },
    id: {
      type: "string",
    },
    longDescription: {
      type: "string",
    },
    name: {
      type: "string",
    },
    querySummaries: {
      $ref: "#/definitions/querySummaries",
    },
    schedulable: {
      type: "boolean",
    },
  },
} as const;

export const builtInConnectorOptionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/builtInConnectorOption",
  },
} as const;

export const builtInSourceConfigSchema = {
  type: "object",
  required: ["connectorId", "handles", "runImmediately", "values"],
  properties: {
    connectorId: {
      type: "string",
    },
    handles: {
      $ref: "#/definitions/handles",
    },
    runImmediately: {
      type: "boolean",
    },
    schedule: {
      type: "string",
      "x-nullable": true,
    },
    values: {
      $ref: "#/definitions/configValues",
    },
  },
} as const;

export const builtInSourceConfigUpdateSchema = {
  type: "object",
  required: ["id", "handles", "runImmediately", "values"],
  properties: {
    handles: {
      $ref: "#/definitions/optionalHandles",
    },
    id: {
      type: "string",
    },
    runImmediately: {
      type: "boolean",
    },
    schedule: {
      type: "string",
      "x-nullable": true,
    },
    values: {
      $ref: "#/definitions/optionalConfigValues",
    },
  },
} as const;

export const builtInSourceInputSchema = {
  type: "object",
  required: ["connectorId", "name"],
  properties: {
    config: {
      $ref: "#/definitions/builtInSourceConfig",
    },
    connectorId: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const campaignSchema = {
  type: "object",
  required: [
    "accessReviews",
    "createdAt",
    "creatorEmail",
    "dueDate",
    "meta",
    "name",
  ],
  properties: {
    accessReviews: {
      $ref: "#/definitions/campaignAccessReviews",
    },
    createdAt: {
      $ref: "#/definitions/dateTime",
    },
    creatorEmail: {
      type: "string",
    },
    dueDate: {
      $ref: "#/definitions/date",
    },
    meta: {
      $ref: "#/definitions/stringObject",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const campaignAccessReviewSchema = {
  type: "object",
  required: [
    "assigneeEmail",
    "assigneeName",
    "completed",
    "createdAt",
    "draft",
    "id",
  ],
  properties: {
    assigneeEmail: {
      type: "string",
    },
    assigneeName: {
      type: "string",
    },
    completed: {
      type: "boolean",
    },
    createdAt: {
      $ref: "#/definitions/dateTime",
    },
    draft: {
      type: "boolean",
    },
    id: {
      type: "integer",
    },
  },
} as const;

export const campaignAccessReviewsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignAccessReview",
  },
} as const;

export const campaignInputSchema = {
  type: "object",
  required: ["dueDate", "name"],
  properties: {
    dueDate: {
      $ref: "#/definitions/date",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const campaignSummariesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignSummary",
  },
} as const;

export const campaignSummarySchema = {
  type: "object",
  required: [
    "createdAt",
    "creatorEmail",
    "dueDate",
    "id",
    "name",
    "nbAccessReviews",
    "nbCompletedAccessReviews",
  ],
  properties: {
    createdAt: {
      $ref: "#/definitions/dateTime",
    },
    creatorEmail: {
      type: "string",
    },
    dueDate: {
      $ref: "#/definitions/date",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    nbAccessReviews: {
      type: "integer",
    },
    nbCompletedAccessReviews: {
      type: "integer",
    },
  },
} as const;

export const campaignTemplateSchema = {
  type: "object",
  required: [
    "assignmentQuestion",
    "broken",
    "columnDefinitions",
    "description",
    "filterColumns",
    "groupAssignments",
    "groupingAttributeTypeName",
    "id",
    "name",
    "rowCondition",
    "rowEntityTypeId",
    "rowEntityTypePlural",
    "rowQuestion",
    "rowSourceId",
    "rowSourceName",
  ],
  properties: {
    assignmentQuestion: {
      type: "string",
    },
    broken: {
      type: "boolean",
    },
    columnDefinitions: {
      $ref: "#/definitions/campaignTemplateColumnDefinitions",
    },
    description: {
      type: "string",
    },
    filterColumns: {
      type: "boolean",
    },
    groupAssignments: {
      $ref: "#/definitions/campaignTemplateGroupAssignments",
    },
    groupingAttributeTypeName: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    rowCondition: {
      $ref: "#/definitions/rawMessage",
    },
    rowDefaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    rowDefaultLabelAttributeTypeName: {
      type: "string",
      "x-nullable": true,
    },
    rowEntityTypeId: {
      type: "string",
    },
    rowEntityTypePlural: {
      type: "string",
    },
    rowQuestion: {
      type: "string",
    },
    rowSourceId: {
      type: "integer",
    },
    rowSourceName: {
      type: "string",
    },
  },
} as const;

export const campaignTemplateColumnDefinitionSchema = {
  type: "object",
  required: [
    "condition",
    "entityTypeId",
    "entityTypePlural",
    "sourceId",
    "sourceName",
  ],
  properties: {
    condition: {
      $ref: "#/definitions/rawMessage",
    },
    defaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    defaultLabelAttributeTypeName: {
      type: "string",
      "x-nullable": true,
    },
    entityTypeId: {
      type: "string",
    },
    entityTypePlural: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
    sourceName: {
      type: "string",
    },
  },
} as const;

export const campaignTemplateColumnDefinitionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignTemplateColumnDefinition",
  },
} as const;

export const campaignTemplateGroupAssignmentSchema = {
  type: "object",
  required: ["assigneeEmail", "assigneeName", "hasAssignee", "status"],
  properties: {
    assigneeEmail: {
      type: "string",
    },
    assigneeName: {
      type: "string",
    },
    groupValue: {
      type: "string",
      "x-nullable": true,
    },
    status: {
      $ref: "#/definitions/campaignTemplateGroupAssignmentStatus",
    },
  },
} as const;

export const campaignTemplateGroupAssignmentInputSchema = {
  type: "object",
  required: ["assigneeEmail", "assigneeName"],
  properties: {
    assigneeEmail: {
      type: "string",
    },
    assigneeName: {
      type: "string",
    },
    groupValue: {
      type: "string",
      "x-nullable": true,
    },
  },
} as const;

export const campaignTemplateGroupAssignmentInputsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignTemplateGroupAssignmentInput",
  },
} as const;

export const campaignTemplateGroupAssignmentStatusSchema = {
  type: "string",
  enum: ["missing", "ok", "unused"],
} as const;

export const campaignTemplateGroupAssignmentsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignTemplateGroupAssignment",
  },
} as const;

export const campaignTemplateInputSchema = {
  type: "object",
  required: [
    "assignmentQuestion",
    "columnDefinitions",
    "description",
    "filterColumns",
    "groupAssignments",
    "groupingAttributeTypeId",
    "name",
    "rowCondition",
    "rowEntityTypeId",
    "rowQuestion",
    "rowSourceId",
  ],
  properties: {
    assignmentQuestion: {
      type: "string",
    },
    columnDefinitions: {
      $ref: "#/definitions/campaignTemplateInputColumnDefinitions",
    },
    description: {
      type: "string",
    },
    filterColumns: {
      type: "boolean",
    },
    groupAssignments: {
      $ref: "#/definitions/campaignTemplateGroupAssignmentInputs",
    },
    groupingAttributeTypeId: {
      type: "string",
    },
    name: {
      type: "string",
    },
    rowCondition: {
      $ref: "#/definitions/rawMessage",
    },
    rowDefaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    rowEntityTypeId: {
      type: "string",
    },
    rowQuestion: {
      type: "string",
    },
    rowSourceId: {
      type: "integer",
    },
  },
} as const;

export const campaignTemplateInputColumnDefinitionSchema = {
  type: "object",
  required: ["condition", "entityTypeId", "sourceId"],
  properties: {
    condition: {
      $ref: "#/definitions/rawMessage",
    },
    defaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const campaignTemplateInputColumnDefinitionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignTemplateInputColumnDefinition",
  },
} as const;

export const campaignTemplateSummariesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/campaignTemplateSummary",
  },
} as const;

export const campaignTemplateSummarySchema = {
  type: "object",
  required: ["description", "id", "name"],
  properties: {
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const campaignTemplateUpdateSchema = {
  type: "object",
  required: [
    "assignmentQuestion",
    "description",
    "filterColumns",
    "groupAssignments",
    "name",
    "rowCondition",
    "rowQuestion",
  ],
  properties: {
    assignmentQuestion: {
      type: "string",
    },
    description: {
      type: "string",
    },
    filterColumns: {
      type: "boolean",
    },
    groupAssignments: {
      $ref: "#/definitions/campaignTemplateGroupAssignmentInputs",
    },
    name: {
      type: "string",
    },
    rowDefaultLabelAttributeTypeId: {
      type: "string",
      "x-nullable": true,
    },
    rowQuestion: {
      type: "string",
    },
  },
} as const;

export const changeRequestStatusSchema = {
  type: "string",
  enum: ["deprecated", "open", "rejected", "resolved"],
} as const;

export const configFileSchema = {
  required: [
    "enableOIDCAuthentication",
    "enablePasswordAuthentication",
    "organisationName",
    "usageLogRetentionYears",
  ],
  properties: {
    enableOIDCAuthentication: {
      type: "boolean",
    },
    enablePasswordAuthentication: {
      type: "boolean",
    },
    lastDataImport: {
      $ref: "#/definitions/optionalDateTime",
    },
    organisationName: {
      type: "string",
    },
    supportPageURL: {
      type: "string",
    },
    usageLogRetentionYears: {
      type: "integer",
    },
  },
} as const;

export const configKeySchema = {
  type: "object",
  required: [
    "booleanDefault",
    "description",
    "integerDefault",
    "name",
    "stringDefault",
    "stringOptional",
    "stringTextarea",
    "type",
  ],
  properties: {
    booleanDefault: {
      type: "boolean",
    },
    description: {
      type: "string",
    },
    integerDefault: {
      type: "integer",
    },
    integerMax: {
      type: "integer",
      "x-nullable": true,
    },
    integerMin: {
      type: "integer",
      "x-nullable": true,
    },
    name: {
      type: "string",
    },
    stringDefault: {
      type: "string",
    },
    stringOptional: {
      type: "boolean",
    },
    stringTextarea: {
      type: "boolean",
    },
    type: {
      $ref: "#/definitions/configKeyType",
    },
  },
} as const;

export const configKeyTypeSchema = {
  type: "string",
  enum: ["boolean", "file", "integer", "secret", "string"],
} as const;

export const configKeysSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/configKey",
  },
} as const;

export const configValueSchema = {
  type: "object",
  required: ["booleanValue", "integerValue", "stringValue"],
  properties: {
    booleanValue: {
      type: "boolean",
    },
    integerValue: {
      type: "integer",
    },
    stringValue: {
      type: "string",
    },
  },
} as const;

export const configValuesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/configValue",
  },
} as const;

export const connectorSchema = {
  type: "object",
  required: ["type"],
  properties: {
    builtInConfigKeys: {
      $ref: "#/definitions/configKeys",
    },
    builtInConfigValues: {
      $ref: "#/definitions/configValues",
    },
    builtInId: {
      type: "string",
      "x-nullable": true,
    },
    builtInSchedule: {
      type: "string",
      "x-nullable": true,
    },
    helpUrl: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/connectorType",
    },
  },
} as const;

export const connectorLogSchema = {
  type: "object",
  required: ["level", "message", "timestamp"],
  properties: {
    level: {
      $ref: "#/definitions/connectorLogLevel",
    },
    message: {
      type: "string",
    },
    timestamp: {
      $ref: "#/definitions/dateTime",
    },
  },
} as const;

export const connectorLogLevelSchema = {
  type: "string",
  enum: ["info", "alert"],
} as const;

export const connectorLogsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/connectorLog",
  },
} as const;

export const connectorLogsPageSchema = {
  type: "object",
  required: ["items", "totalCount"],
  properties: {
    items: {
      $ref: "#/definitions/connectorLogs",
    },
    totalCount: {
      type: "integer",
    },
  },
} as const;

export const connectorTypeSchema = {
  type: "string",
  enum: ["builtIn", "custom"],
} as const;

export const customSourceInputSchema = {
  type: "object",
  required: ["entityTypes", "name"],
  properties: {
    attributeTypes: {
      $ref: "#/definitions/attributeTypeInputs",
    },
    entityTypes: {
      $ref: "#/definitions/entityTypeInputs",
    },
    name: {
      type: "string",
    },
    relationshipAttributeTypes: {
      $ref: "#/definitions/relationshipAttributeTypeInputs",
    },
    relationshipTypes: {
      $ref: "#/definitions/relationshipTypeInputs",
    },
  },
} as const;

export const dashboardCardSchema = {
  type: "object",
  required: ["type"],
  properties: {
    cols: {
      type: "integer",
    },
    description: {
      type: "string",
    },
    entityType: {
      type: "string",
    },
    groupByDefault: {
      type: "string",
    },
    queryID: {
      type: "integer",
    },
    rows: {
      type: "integer",
    },
    scopeID: {
      type: "integer",
    },
    showEstimationLine: {
      type: "boolean",
      "x-nullable": true,
    },
    showTotalCount: {
      type: "boolean",
      "x-nullable": true,
    },
    sourceID: {
      type: "integer",
      "x-nullable": true,
    },
    startDate: {
      type: "string",
      format: "date-time",
    },
    targetDate: {
      type: "string",
      format: "date-time",
    },
    targetValue: {
      type: "integer",
      "x-nullable": true,
    },
    title: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/dashboardCardType",
    },
    yAxisMode: {
      $ref: "#/definitions/yAxisMode",
    },
  },
} as const;

export const dashboardCardTypeSchema = {
  type: "string",
  enum: [
    "burnDown",
    "queryDiffChart",
    "scopeSummary",
    "scopeTimeSeries",
    "sectionTitle",
    "storedQueryGrouping",
    "storedQuerySummary",
    "storedQueryTimeSeries",
    "summary",
  ],
} as const;

export const dashboardCardsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/dashboardCard",
  },
} as const;

export const dateSchema = {
  type: "string",
  format: "date",
} as const;

export const dateTimeSchema = {
  type: "string",
  format: "date-time",
} as const;

export const defaultAccessProfileSchema = {
  type: "object",
  required: ["permittedSources"],
  properties: {
    permittedSources: {
      $ref: "#/definitions/permittedSources",
    },
  },
} as const;

export const domainGraphSchemaSchema = {
  type: "object",
  required: [
    "entityTypes",
    "entityAttributeTypes",
    "relationshipAttributeTypes",
    "relationshipTypes",
  ],
  properties: {
    entityAttributeTypes: {
      $ref: "#/definitions/attributeTypes",
    },
    entityTypes: {
      $ref: "#/definitions/entityTypes",
    },
    relationshipAttributeTypes: {
      $ref: "#/definitions/relationshipAttributeTypes",
    },
    relationshipTypes: {
      $ref: "#/definitions/relationshipTypes",
    },
  },
} as const;

export const emailSchema = {
  type: "string",
  format: "email",
} as const;

export const emailsSchema = {
  type: "array",
  uniqueItems: true,
  items: {
    $ref: "#/definitions/email",
  },
} as const;

export const entitiesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/entity",
  },
} as const;

export const entitySchema = {
  type: "object",
  required: ["attributeAssignments", "id", "internalId", "name"],
  properties: {
    attributeAssignments: {
      $ref: "#/definitions/attributeAssignments",
    },
    id: {
      type: "string",
    },
    internalId: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const entityAttributeTypeUpdateSchema = {
  type: "object",
  required: ["archived", "description", "name"],
  properties: {
    archived: {
      type: "boolean",
    },
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const entityDeltaSchema = {
  type: "object",
  required: ["after", "before", "entityType"],
  properties: {
    after: {
      type: "integer",
    },
    before: {
      type: "integer",
    },
    entityType: {
      type: "string",
    },
  },
} as const;

export const entityDeltasSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/entityDelta",
  },
} as const;

export const entityRemovalRequestSchema = {
  type: "object",
  required: [
    "accessReviewId",
    "campaignId",
    "comment",
    "entityName",
    "entityId",
    "entityTypeId",
    "entityTypeSingular",
    "id",
    "requestedAt",
    "requestedBy",
    "sourceId",
    "sourceName",
    "status",
  ],
  properties: {
    accessReviewId: {
      type: "integer",
    },
    campaignId: {
      type: "integer",
    },
    comment: {
      type: "string",
    },
    entityId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    entityTypeSingular: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    requestedAt: {
      $ref: "#/definitions/dateTime",
    },
    requestedBy: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
    sourceName: {
      type: "string",
    },
    status: {
      $ref: "#/definitions/changeRequestStatus",
    },
  },
} as const;

export const entityRemovalRequestInputSchema = {
  type: "object",
  required: ["comment", "entityId", "entityTypeId", "sourceId"],
  properties: {
    comment: {
      type: "string",
    },
    entityId: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const entityRemovalRequestPageSchema = {
  type: "object",
  required: ["items", "totalCount"],
  properties: {
    items: {
      $ref: "#/definitions/entityRemovalRequests",
    },
    totalCount: {
      type: "integer",
    },
  },
} as const;

export const entityRemovalRequestsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/entityRemovalRequest",
  },
} as const;

export const entitySearchSchema = {
  type: "object",
  required: ["entityExternalIds", "entityTypeId", "sourceId"],
  properties: {
    entityExternalIds: {
      $ref: "#/definitions/strings",
    },
    entityIds: {
      $ref: "#/definitions/uniqueIntegers",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const entityTypeSchema = {
  type: "object",
  required: ["anonymized", "icon", "id", "plural", "singular"],
  properties: {
    anonymized: {
      type: "boolean",
    },
    icon: {
      type: "string",
    },
    id: {
      type: "string",
    },
    plural: {
      type: "string",
    },
    singular: {
      type: "string",
    },
  },
} as const;

export const entityTypeDetailsSchema = {
  type: "object",
  required: ["anonymized", "icon", "plural", "singular"],
  properties: {
    anonymized: {
      type: "boolean",
    },
    icon: {
      type: "string",
    },
    plural: {
      type: "string",
    },
    singular: {
      type: "string",
    },
  },
} as const;

export const entityTypeIdSchema = {
  type: "string",
  pattern: "^[^-\\t\\r+=@]",
} as const;

export const entityTypeInputSchema = {
  type: "object",
  required: ["icon", "id", "index", "plural", "singular"],
  properties: {
    icon: {
      type: "string",
    },
    id: {
      $ref: "#/definitions/entityTypeId",
    },
    index: {
      type: "integer",
    },
    plural: {
      type: "string",
    },
    singular: {
      type: "string",
    },
  },
} as const;

export const entityTypeInputV2Schema = {
  type: "object",
  required: ["icon", "id", "plural", "singular"],
  properties: {
    icon: {
      type: "string",
    },
    id: {
      $ref: "#/definitions/entityTypeId",
    },
    plural: {
      type: "string",
    },
    singular: {
      type: "string",
    },
  },
} as const;

export const entityTypeInputsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/entityTypeInputV2",
  },
} as const;

export const entityTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/entityType",
  },
} as const;

export const evaluationSchema = {
  type: "object",
  required: ["includeEntityRemovalRequests", "query"],
  properties: {
    includeEntityRemovalRequests: {
      type: "boolean",
    },
    includeRelationshipRemovalRequestsFrom: {
      type: "string",
      "x-nullable": true,
    },
    query: {
      $ref: "#/definitions/rawMessage",
    },
  },
} as const;

export const evaluationBadRequestResponseSchema = {
  type: "object",
  required: ["category"],
  properties: {
    category: {
      $ref: "#/definitions/evaluationBadRequestResponseCategory",
    },
    errorMessage: {
      type: "string",
    },
  },
} as const;

export const evaluationBadRequestResponseCategorySchema = {
  type: "string",
  enum: ["archivedAttributeType", "other"],
} as const;

export const evaluationsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/evaluation",
  },
} as const;

export const groupByQueryResultSchema = {
  type: "object",
  required: ["count", "label", "subPages"],
  properties: {
    count: {
      type: "integer",
    },
    label: {
      $ref: "#/definitions/value",
    },
    subPages: {
      $ref: "#/definitions/groupByQueryResultsPage",
    },
  },
} as const;

export const groupByQueryResultsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/groupByQueryResult",
  },
} as const;

export const groupByQueryResultsPageSchema = {
  type: "object",
  required: ["groupCount", "results"],
  properties: {
    groupCount: {
      type: "integer",
    },
    results: {
      $ref: "#/definitions/groupByQueryResults",
    },
  },
} as const;

export const groupByQueryResultsPagesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/groupByQueryResultsPage",
  },
} as const;

export const handleSchema = {
  type: "object",
  required: ["id", "token"],
  properties: {
    id: {
      type: "integer",
    },
    token: {
      type: "string",
    },
  },
} as const;

export const handlesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/handle",
  },
} as const;

export const inviteSchema = {
  type: "object",
  required: ["id", "email", "expiry", "profileIds", "role"],
  properties: {
    creationTs: {
      $ref: "#/definitions/optionalDateTime",
    },
    email: {
      type: "string",
    },
    expiry: {
      $ref: "#/definitions/dateTime",
    },
    id: {
      type: "integer",
    },
    profileIds: {
      $ref: "#/definitions/uniqueIntegers",
    },
    role: {
      $ref: "#/definitions/role",
    },
  },
} as const;

export const inviteSetSchema = {
  type: "object",
  required: ["emails", "profileIds", "role"],
  properties: {
    emails: {
      $ref: "#/definitions/emails",
    },
    profileIds: {
      $ref: "#/definitions/uniqueIntegers",
    },
    role: {
      $ref: "#/definitions/role",
    },
  },
} as const;

export const invitesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/invite",
  },
} as const;

export const linkingStrategiesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/linkingStrategy",
  },
} as const;

export const linkingStrategySchema = {
  type: "object",
  required: [
    "fromEntityTypeId",
    "fromSourceId",
    "toEntityTypeId",
    "toSourceId",
  ],
  properties: {
    fromEntityTypeId: {
      type: "string",
    },
    fromSourceId: {
      type: "integer",
    },
    toEntityTypeId: {
      type: "string",
    },
    toSourceId: {
      type: "integer",
    },
  },
} as const;

export const linkingStrategyConditionSchema = {
  type: "object",
  required: ["matchCaseSensitive", "matchOperator"],
  properties: {
    fromAttributeTypeId: {
      type: "string",
    },
    fromProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
    matchCaseSensitive: {
      type: "boolean",
    },
    matchOperator: {
      $ref: "#/definitions/matchOperator",
    },
    toAttributeTypeId: {
      type: "string",
    },
    toProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
  },
} as const;

export const linkingStrategyDetailsSchema = {
  type: "object",
  required: [
    "fromEntityTypeId",
    "fromSourceId",
    "id",
    "matchCaseSensitive",
    "matchOperator",
    "toEntityTypeId",
    "toSourceId",
  ],
  properties: {
    fromAttributeTypeId: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    fromProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
    fromSourceId: {
      type: "integer",
    },
    id: {
      type: "integer",
    },
    matchCaseSensitive: {
      type: "boolean",
    },
    matchOperator: {
      $ref: "#/definitions/matchOperator",
    },
    toAttributeTypeId: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    toProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
    toSourceId: {
      type: "integer",
    },
  },
} as const;

export const linkingStrategyDetailsListSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/linkingStrategyDetails",
  },
} as const;

export const linkingStrategyInputSchema = {
  type: "object",
  required: [
    "fromEntityTypeId",
    "fromSourceId",
    "matchCaseSensitive",
    "matchOperator",
    "toEntityTypeId",
    "toSourceId",
  ],
  properties: {
    fromAttributeTypeId: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    fromProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
    fromSourceId: {
      type: "integer",
    },
    matchCaseSensitive: {
      type: "boolean",
    },
    matchOperator: {
      $ref: "#/definitions/matchOperator",
    },
    toAttributeTypeId: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    toProperty: {
      $ref: "#/definitions/linkingStrategyProperty",
    },
    toSourceId: {
      type: "integer",
    },
  },
} as const;

export const linkingStrategyPropertySchema = {
  type: "string",
  enum: ["id", "name"],
} as const;

export const manualImportContentSchema = {
  type: "object",
  required: ["entityTypes", "relationshipTypes", "sourceName"],
  properties: {
    entityTypes: {
      $ref: "#/definitions/manualImportContentEntityTypes",
    },
    relationshipTypes: {
      $ref: "#/definitions/manualImportContentRelationshipTypes",
    },
    sourceName: {
      type: "string",
    },
  },
} as const;

export const manualImportContentAttributeTypeSchema = {
  type: "object",
  required: ["id", "name", "type"],
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const manualImportContentAttributeTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/manualImportContentAttributeType",
  },
} as const;

export const manualImportContentEntityTypeSchema = {
  type: "object",
  required: ["attributeTypes", "entities", "id", "label"],
  properties: {
    attributeTypes: {
      $ref: "#/definitions/manualImportContentAttributeTypes",
    },
    entities: {
      $ref: "#/definitions/entities",
    },
    id: {
      type: "string",
    },
    label: {
      type: "string",
    },
  },
} as const;

export const manualImportContentEntityTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/manualImportContentEntityType",
  },
} as const;

export const manualImportContentRelationshipSchema = {
  type: "object",
  required: ["fromEntityId", "fromEntityName", "toEntityId", "toEntityName"],
  properties: {
    fromEntityId: {
      type: "string",
    },
    fromEntityName: {
      type: "string",
    },
    toEntityId: {
      type: "string",
    },
    toEntityName: {
      type: "string",
    },
  },
} as const;

export const manualImportContentRelationshipTypeSchema = {
  type: "object",
  required: [
    "fromEntityTypeId",
    "fromEntityTypeSingular",
    "relationships",
    "toEntityTypeId",
    "toEntityTypeSingular",
  ],
  properties: {
    fromEntityTypeId: {
      type: "string",
    },
    fromEntityTypeSingular: {
      type: "string",
    },
    relationships: {
      $ref: "#/definitions/manualImportContentRelationships",
    },
    toEntityTypeId: {
      type: "string",
    },
    toEntityTypeSingular: {
      type: "string",
    },
  },
} as const;

export const manualImportContentRelationshipTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/manualImportContentRelationshipType",
  },
} as const;

export const manualImportContentRelationshipsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/manualImportContentRelationship",
  },
} as const;

export const matchOperatorSchema = {
  type: "string",
  enum: [
    "contains",
    "endsWith",
    "equals",
    "isPrefixOf",
    "isSubstringOf",
    "isSuffixOf",
    "startsWith",
  ],
} as const;

export const metaSchema = {
  type: "object",
  required: ["linkingStrategies", "sources"],
  properties: {
    linkingStrategies: {
      $ref: "#/definitions/linkingStrategies",
    },
    sources: {
      $ref: "#/definitions/sources",
    },
  },
} as const;

export const notificationChannelSchema = {
  type: "object",
  required: ["description", "email", "emailVerified", "id", "name"],
  properties: {
    description: {
      type: "string",
    },
    email: {
      type: "string",
    },
    emailVerified: {
      type: "boolean",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const notificationChannelInputSchema = {
  type: "object",
  required: ["description", "email", "id", "name", "resendVerificationEmail"],
  properties: {
    description: {
      type: "string",
    },
    email: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    resendVerificationEmail: {
      type: "boolean",
    },
  },
} as const;

export const notificationChannelsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/notificationChannel",
  },
} as const;

export const optionalConfigValueSchema = {
  type: "object",
  properties: {
    value: {
      $ref: "#/definitions/configValue",
    },
  },
} as const;

export const optionalConfigValuesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/optionalConfigValue",
  },
} as const;

export const optionalDateTimeSchema = {
  type: "string",
  format: "date-time",
  "x-nullable": true,
} as const;

export const optionalHandleSchema = {
  type: "object",
  properties: {
    value: {
      $ref: "#/definitions/handle",
    },
  },
} as const;

export const optionalHandlesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/optionalHandle",
  },
} as const;

export const passwordResetBodySchema = {
  type: "object",
  required: ["newPassword", "token"],
  properties: {
    newPassword: {
      type: "string",
    },
    token: {
      type: "string",
    },
  },
} as const;

export const passwordResetRequestBodySchema = {
  type: "object",
  required: ["email"],
  properties: {
    email: {
      type: "string",
    },
  },
} as const;

export const peerReviewCollectionSchema = {
  type: "object",
  required: [
    "broken",
    "description",
    "groupingAttributeTypeName",
    "groupValues",
    "id",
    "includeNotAssignedGroup",
    "name",
  ],
  properties: {
    broken: {
      type: "boolean",
    },
    description: {
      type: "string",
    },
    groupValues: {
      $ref: "#/definitions/strings",
    },
    groupingAttributeTypeName: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    includeNotAssignedGroup: {
      type: "boolean",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const peerReviewCollectionColumnDefinitionSchema = {
  type: "object",
  required: ["condition", "entityTypeId", "sourceId"],
  properties: {
    condition: {
      $ref: "#/definitions/rawMessage",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const peerReviewCollectionColumnDefinitionsSchema = {
  type: "array",
  minItems: 1,
  items: {
    $ref: "#/definitions/peerReviewCollectionColumnDefinition",
  },
} as const;

export const peerReviewCollectionEntitySetSchema = {
  type: "object",
  required: ["entities", "entityTypeId", "sourceId"],
  properties: {
    entities: {
      $ref: "#/definitions/entities",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const peerReviewCollectionEntitySetsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/peerReviewCollectionEntitySet",
  },
} as const;

export const peerReviewCollectionGroupSchema = {
  type: "object",
  required: [
    "columnEntitySets",
    "rowEntities",
    "rowEntityTypeId",
    "rowSourceId",
  ],
  properties: {
    columnEntitySets: {
      $ref: "#/definitions/peerReviewCollectionEntitySets",
    },
    rowEntities: {
      $ref: "#/definitions/entities",
    },
    rowEntityTypeId: {
      type: "string",
    },
    rowSourceId: {
      type: "integer",
    },
  },
} as const;

export const peerReviewCollectionInputSchema = {
  type: "object",
  required: [
    "columnDefinitions",
    "description",
    "filterColumns",
    "groupingAttributeTypeId",
    "name",
    "rowCondition",
    "rowEntityTypeId",
    "rowSourceId",
  ],
  properties: {
    columnDefinitions: {
      $ref: "#/definitions/peerReviewCollectionColumnDefinitions",
    },
    description: {
      type: "string",
    },
    filterColumns: {
      type: "boolean",
    },
    groupingAttributeTypeId: {
      type: "string",
    },
    name: {
      type: "string",
    },
    rowCondition: {
      $ref: "#/definitions/rawMessage",
    },
    rowEntityTypeId: {
      type: "string",
    },
    rowSourceId: {
      type: "integer",
    },
  },
} as const;

export const peerReviewCollectionSummariesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/peerReviewCollectionSummary",
  },
} as const;

export const peerReviewCollectionSummarySchema = {
  type: "object",
  required: ["description", "id", "name"],
  properties: {
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const permittedAttributeSetSchema = {
  type: "object",
  required: ["attributeTypeIds", "entityType"],
  properties: {
    attributeTypeIds: {
      $ref: "#/definitions/strings",
    },
    entityType: {
      type: "string",
    },
  },
} as const;

export const permittedAttributeSetsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/permittedAttributeSet",
  },
} as const;

export const permittedRelationshipAttributeSetSchema = {
  type: "object",
  required: ["entityTypeFrom", "entityTypeTo", "relationshipAttributeTypeIds"],
  properties: {
    entityTypeFrom: {
      type: "string",
    },
    entityTypeTo: {
      type: "string",
    },
    relationshipAttributeTypeIds: {
      $ref: "#/definitions/strings",
    },
  },
} as const;

export const permittedRelationshipAttributeSetsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/permittedRelationshipAttributeSet",
  },
} as const;

export const permittedSourceSchema = {
  type: "object",
  required: [
    "permittedAttributeSets",
    "permittedRelationshipAttributeSets",
    "sourceID",
  ],
  properties: {
    importsAllowed: {
      type: "boolean",
    },
    permittedAttributeSets: {
      $ref: "#/definitions/permittedAttributeSets",
    },
    permittedRelationshipAttributeSets: {
      $ref: "#/definitions/permittedRelationshipAttributeSets",
    },
    sourceID: {
      type: "integer",
    },
  },
} as const;

export const permittedSourcesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/permittedSource",
  },
} as const;

export const positiveIntegerSchema = {
  type: "integer",
  minimum: 1,
} as const;

export const profileSchema = {
  type: "object",
  required: ["authMode", "email", "firstName", "id", "lastName", "role"],
  properties: {
    authMode: {
      $ref: "#/definitions/authMode",
    },
    email: {
      type: "string",
    },
    firstName: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    lastName: {
      type: "string",
    },
    role: {
      $ref: "#/definitions/role",
    },
  },
} as const;

export const profileInputSchema = {
  type: "object",
  required: ["firstName", "lastName"],
  properties: {
    firstName: {
      type: "string",
    },
    lastName: {
      type: "string",
    },
  },
} as const;

export const queryResultSchema = {
  type: "object",
  required: [
    "entity",
    "inclusions",
    "linkGroupByPages",
    "linkPages",
    "removalRequests",
  ],
  properties: {
    entity: {
      $ref: "#/definitions/queryResultEntity",
    },
    inclusions: {
      $ref: "#/definitions/queryResultInclusions",
    },
    linkGroupByPages: {
      $ref: "#/definitions/groupByQueryResultsPages",
    },
    linkPages: {
      $ref: "#/definitions/queryResultsPages",
    },
    removalRequests: {
      $ref: "#/definitions/removalRequests",
    },
  },
} as const;

export const queryResultEntitySchema = {
  type: "object",
  required: ["active", "id", "name"],
  properties: {
    active: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const queryResultInclusionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/value",
  },
} as const;

export const queryResultsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/queryResult",
  },
} as const;

export const queryResultsPageSchema = {
  type: "object",
  required: ["count", "results"],
  properties: {
    count: {
      type: "integer",
    },
    results: {
      $ref: "#/definitions/queryResults",
    },
  },
} as const;

export const queryResultsPagesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/queryResultsPage",
  },
} as const;

export const queryScopeSchema = {
  type: "object",
  required: ["id", "name"],
  properties: {
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const querySummariesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/querySummary",
  },
} as const;

export const querySummarySchema = {
  type: "object",
  required: ["description", "name"],
  properties: {
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const rawMessageSchema = {
  "x-go-type": {
    hints: {
      kind: "interface",
      noValidation: true,
    },
    import: {
      package: "encoding/json",
    },
    type: "RawMessage",
  },
} as const;

export const rawMessagesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/rawMessage",
  },
} as const;

export const relationshipAttributeTypeSchema = {
  type: "object",
  required: ["archived", "childType", "id", "name", "parentType", "type"],
  properties: {
    archived: {
      type: "boolean",
    },
    childType: {
      type: "string",
    },
    description: {
      type: "string",
      "x-nullable": true,
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    parentType: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const relationshipAttributeTypeInputSchema = {
  type: "object",
  required: [
    "description",
    "fromEntityTypeId",
    "id",
    "toEntityTypeId",
    "name",
    "type",
  ],
  properties: {
    description: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    type: {
      $ref: "#/definitions/type",
    },
  },
} as const;

export const relationshipAttributeTypeInputsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipAttributeTypeInput",
  },
} as const;

export const relationshipAttributeTypeUpdateSchema = {
  type: "object",
  required: ["archived", "description", "name"],
  properties: {
    archived: {
      type: "boolean",
    },
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const relationshipAttributeTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipAttributeType",
  },
} as const;

export const relationshipChangeRequestSchema = {
  type: "object",
  required: [
    "accessReviewId",
    "campaignId",
    "comment",
    "fromEntityName",
    "fromEntityId",
    "fromEntityTypeId",
    "fromEntityTypeSingular",
    "fromSourceId",
    "fromSourceName",
    "id",
    "operation",
    "requestedAt",
    "requestedBy",
    "status",
    "toEntityName",
    "toEntityId",
    "toEntityTypeId",
    "toEntityTypeSingular",
    "toSourceId",
    "toSourceName",
  ],
  properties: {
    accessReviewId: {
      type: "integer",
    },
    campaignId: {
      type: "integer",
    },
    comment: {
      type: "string",
    },
    fromEntityId: {
      type: "string",
    },
    fromEntityName: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    fromEntityTypeSingular: {
      type: "string",
    },
    fromSourceId: {
      type: "integer",
    },
    fromSourceName: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    operation: {
      $ref: "#/definitions/relationshipChangeRequestOperation",
    },
    requestedAt: {
      $ref: "#/definitions/dateTime",
    },
    requestedBy: {
      type: "string",
    },
    status: {
      $ref: "#/definitions/changeRequestStatus",
    },
    toEntityId: {
      type: "string",
    },
    toEntityName: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    toEntityTypeSingular: {
      type: "string",
    },
    toSourceId: {
      type: "integer",
    },
    toSourceName: {
      type: "string",
    },
  },
} as const;

export const relationshipChangeRequestOperationSchema = {
  type: "string",
  enum: ["add", "remove"],
} as const;

export const relationshipChangeRequestPageSchema = {
  type: "object",
  required: ["items", "totalCount"],
  properties: {
    items: {
      $ref: "#/definitions/relationshipChangeRequests",
    },
    totalCount: {
      type: "integer",
    },
  },
} as const;

export const relationshipChangeRequestsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipChangeRequest",
  },
} as const;

export const relationshipDeltaSchema = {
  type: "object",
  required: ["after", "before", "entityTypeFrom", "entityTypeTo"],
  properties: {
    after: {
      type: "integer",
    },
    before: {
      type: "integer",
    },
    entityTypeFrom: {
      type: "string",
    },
    entityTypeTo: {
      type: "string",
    },
  },
} as const;

export const relationshipDeltasSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipDelta",
  },
} as const;

export const relationshipRemovalRequestSchema = {
  type: "object",
  required: [
    "comment",
    "fromEntityId",
    "fromEntityTypeId",
    "fromSourceId",
    "toEntityId",
    "toEntityTypeId",
    "toSourceId",
  ],
  properties: {
    comment: {
      type: "string",
    },
    fromEntityId: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    fromSourceId: {
      type: "integer",
    },
    toEntityId: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    toSourceId: {
      type: "integer",
    },
  },
} as const;

export const relationshipSearchSchema = {
  type: "object",
  required: ["columnEntityIds", "rowEntityIds"],
  properties: {
    columnEntityIds: {
      $ref: "#/definitions/uniqueIntegers",
    },
    rowEntityIds: {
      $ref: "#/definitions/uniqueIntegers",
    },
  },
} as const;

export const relationshipTypeSchema = {
  type: "object",
  required: [
    "fromEntityTypeId",
    "id",
    "toEntityTypeId",
    "withoutRelationships",
  ],
  properties: {
    fromEntityTypeId: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    toEntityTypeId: {
      type: "string",
    },
    withoutRelationships: {
      type: "boolean",
    },
  },
} as const;

export const relationshipTypeInputSchema = {
  type: "object",
  required: ["fromEntityTypeId", "toEntityTypeId"],
  properties: {
    fromEntityTypeId: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
  },
} as const;

export const relationshipTypeInputsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipTypeInput",
  },
} as const;

export const relationshipTypesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/relationshipType",
  },
} as const;

export const relationshipsSchema = {
  type: "object",
  additionalProperties: {
    type: "integer",
  },
} as const;

export const reloadEventSchema = {
  type: "object",
  required: ["status", "timeStarted"],
  properties: {
    status: {
      $ref: "#/definitions/reloadEventStatus",
    },
    timeStarted: {
      $ref: "#/definitions/dateTime",
    },
  },
} as const;

export const reloadEventStatusSchema = {
  type: "object",
  required: ["type"],
  properties: {
    clientErrorMessage: {
      type: "string",
    },
    clientErrorTimeEnded: {
      $ref: "#/definitions/dateTime",
    },
    serverErrorTimeEnded: {
      $ref: "#/definitions/dateTime",
    },
    successEntityDeltas: {
      $ref: "#/definitions/entityDeltas",
    },
    successRelationshipDeltas: {
      $ref: "#/definitions/relationshipDeltas",
    },
    successTimeEnded: {
      $ref: "#/definitions/dateTime",
    },
    type: {
      $ref: "#/definitions/reloadEventStatusType",
    },
  },
} as const;

export const reloadEventStatusTypeSchema = {
  type: "string",
  enum: ["clientError", "inProgress", "serverError", "success"],
} as const;

export const reloadEventsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/reloadEvent",
  },
} as const;

export const removalRequestSchema = {
  type: "object",
  required: ["comment", "requestedAt", "requestedBy"],
  properties: {
    comment: {
      type: "string",
    },
    requestedAt: {
      $ref: "#/definitions/dateTime",
    },
    requestedBy: {
      type: "string",
    },
  },
} as const;

export const removalRequestsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/removalRequest",
  },
} as const;

export const retentionYearsSchema = {
  type: "integer",
  maximum: 10,
  minimum: 1,
} as const;

export const roleSchema = {
  type: "string",
  enum: [
    "member",
    "connectorAdmin",
    "admin",
    "accessReviewManager",
    "changeRequestManager",
    "editor",
  ],
} as const;

export const roleBodySchema = {
  type: "object",
  required: ["role"],
  properties: {
    role: {
      $ref: "#/definitions/role",
    },
  },
} as const;

export const scopeSchema = {
  required: [
    "description",
    "id",
    "name",
    "ownerId",
    "ownerEmail",
    "shared",
    "showTotalCount",
  ],
  properties: {
    description: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    ownerEmail: {
      type: "string",
    },
    ownerId: {
      type: "integer",
    },
    shared: {
      type: "boolean",
    },
    showTotalCount: {
      type: "boolean",
    },
  },
} as const;

export const scopeInputSchema = {
  type: "object",
  required: ["description", "name", "shared"],
  properties: {
    description: {
      type: "string",
    },
    name: {
      type: "string",
    },
    shared: {
      type: "boolean",
    },
    showTotalCount: {
      type: "boolean",
    },
  },
} as const;

export const scopeQueriesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/storedQueryDetails",
  },
} as const;

export const scopesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/scope",
  },
} as const;

export const snapshotSchema = {
  type: "string",
  format: "binary",
} as const;

export const sourceSchema = {
  type: "object",
  required: [
    "archived",
    "builtInConnectorId",
    "domainGraphSchema",
    "id",
    "importsAllowed",
    "name",
  ],
  properties: {
    archived: {
      type: "boolean",
    },
    builtInConnectorId: {
      type: "string",
    },
    domainGraphSchema: {
      $ref: "#/definitions/domainGraphSchema",
    },
    id: {
      type: "integer",
    },
    importsAllowed: {
      type: "boolean",
    },
    lastReloadTimestamp: {
      $ref: "#/definitions/optionalDateTime",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const sourceCsvImportSchema = {
  type: "object",
  required: ["snapshot"],
  properties: {
    configuration: {
      $ref: "#/definitions/sourceCsvImportConfiguration",
    },
    snapshot: {
      $ref: "#/definitions/sourceCsvImportSnapshot",
    },
  },
} as const;

export const sourceCsvImportConfigurationSchema = {
  type: "object",
  required: [
    "dateFormat",
    "dateTimeFormat",
    "delimiter",
    "emptyValue",
    "timeFormat",
    "trimWhitespace",
  ],
  properties: {
    dateFormat: {
      type: "string",
    },
    dateTimeFormat: {
      type: "string",
    },
    delimiter: {
      type: "string",
    },
    emptyValue: {
      type: "string",
    },
    timeFormat: {
      type: "string",
    },
    trimWhitespace: {
      type: "boolean",
    },
  },
} as const;

export const sourceCsvImportSnapshotSchema = {
  type: "string",
  format: "byte",
} as const;

export const sourceDetailsSchema = {
  type: "object",
  required: [
    "archived",
    "connector",
    "csvImportDateFormat",
    "csvImportDateTimeFormat",
    "csvImportDelimiter",
    "csvImportEmptyValue",
    "csvImportTimeFormat",
    "csvImportTrimWhitespace",
    "domainGraphSchema",
    "healthCheckEmailAddresses",
    "healthCheckSnapshotMaxAge",
    "manualImportDisabled",
    "name",
    "queryResultHistoryRetentionYears",
  ],
  properties: {
    archived: {
      type: "boolean",
    },
    connector: {
      $ref: "#/definitions/connector",
    },
    csvImportDateFormat: {
      type: "string",
    },
    csvImportDateTimeFormat: {
      type: "string",
    },
    csvImportDelimiter: {
      type: "string",
    },
    csvImportEmptyValue: {
      type: "string",
    },
    csvImportTimeFormat: {
      type: "string",
    },
    csvImportTrimWhitespace: {
      type: "boolean",
    },
    domainGraphSchema: {
      $ref: "#/definitions/domainGraphSchema",
    },
    healthCheckEmailAddresses: {
      $ref: "#/definitions/strings",
    },
    healthCheckSnapshotMaxAge: {
      $ref: "#/definitions/positiveInteger",
    },
    manualImportDisabled: {
      type: "boolean",
    },
    name: {
      type: "string",
    },
    queryResultHistoryRetentionYears: {
      $ref: "#/definitions/retentionYears",
    },
  },
} as const;

export const sourceHealthCheckConfigurationSchema = {
  type: "object",
  required: ["emailAddresses", "snapshotMaxAge"],
  properties: {
    emailAddresses: {
      $ref: "#/definitions/strings",
    },
    snapshotMaxAge: {
      $ref: "#/definitions/positiveInteger",
    },
  },
} as const;

export const sourcesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/source",
  },
} as const;

export const storedQueriesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/storedQuery",
  },
} as const;

export const storedQuerySchema = {
  type: "object",
  required: [
    "description",
    "highThreshold",
    "id",
    "isControl",
    "mediumThreshold",
    "name",
    "ownerEmail",
    "ownerId",
    "shared",
    "sourceId",
    "storedQueryData",
  ],
  properties: {
    description: {
      type: "string",
    },
    highThreshold: {
      type: "integer",
    },
    id: {
      type: "integer",
    },
    isControl: {
      type: "boolean",
    },
    mediumThreshold: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    ownerEmail: {
      type: "string",
    },
    ownerId: {
      type: "integer",
    },
    resultCountAtLastReload: {
      type: "integer",
      "x-nullable": true,
    },
    scope: {
      $ref: "#/definitions/queryScope",
    },
    shared: {
      type: "boolean",
    },
    sourceId: {
      type: "integer",
    },
    storedQueryData: {
      $ref: "#/definitions/storedQueryData",
    },
  },
} as const;

export const storedQueryDataSchema = {
  type: "object",
  required: ["alias", "condition", "entityType"],
  properties: {
    alias: {
      type: "string",
    },
    condition: {
      $ref: "#/definitions/rawMessage",
    },
    entityType: {
      type: "string",
    },
  },
} as const;

export const storedQueryDetailsSchema = {
  type: "object",
  required: [
    "description",
    "highThreshold",
    "historyPoints",
    "id",
    "isControl",
    "mediumThreshold",
    "name",
    "ownerEmail",
    "ownerId",
    "shared",
    "sourceId",
    "storedQueryData",
  ],
  properties: {
    description: {
      type: "string",
    },
    highThreshold: {
      type: "integer",
    },
    historyPoints: {
      $ref: "#/definitions/storedQueryHistoryPoints",
    },
    id: {
      type: "integer",
    },
    isControl: {
      type: "boolean",
    },
    mediumThreshold: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    ownerEmail: {
      type: "string",
    },
    ownerId: {
      type: "integer",
    },
    resultCountAtLastReload: {
      type: "integer",
      "x-nullable": true,
    },
    scope: {
      $ref: "#/definitions/queryScope",
    },
    shared: {
      type: "boolean",
    },
    sourceId: {
      type: "integer",
    },
    storedQueryData: {
      $ref: "#/definitions/storedQueryData",
    },
  },
} as const;

export const storedQueryHistoryItemSchema = {
  type: "object",
  required: ["addition", "entityExternalId", "entityName"],
  properties: {
    addition: {
      type: "boolean",
    },
    entityExternalId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
  },
} as const;

export const storedQueryHistoryItemsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/storedQueryHistoryItem",
  },
} as const;

export const storedQueryHistoryPointSchema = {
  type: "object",
  required: ["id", "nbAdditions", "nbDeletions", "timestamp"],
  properties: {
    id: {
      type: "integer",
    },
    nbAdditions: {
      type: "integer",
    },
    nbDeletions: {
      type: "integer",
    },
    timestamp: {
      $ref: "#/definitions/dateTime",
    },
  },
} as const;

export const storedQueryHistoryPointsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/storedQueryHistoryPoint",
  },
} as const;

export const storedQueryInputSchema = {
  type: "object",
  required: [
    "description",
    "highThreshold",
    "isControl",
    "mediumThreshold",
    "name",
    "shared",
    "sourceId",
    "storedQueryData",
  ],
  properties: {
    description: {
      type: "string",
    },
    highThreshold: {
      type: "integer",
    },
    isControl: {
      type: "boolean",
    },
    mediumThreshold: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    scopeID: {
      type: "integer",
      "x-nullable": true,
    },
    shared: {
      type: "boolean",
    },
    sourceId: {
      type: "integer",
    },
    storedQueryData: {
      $ref: "#/definitions/storedQueryData",
    },
  },
} as const;

export const storedQuerySubscriptionSchema = {
  type: "object",
  required: [
    "channelName",
    "conditionResultsChangedAddition",
    "conditionResultsChangedMinPct",
    "conditionThresholdCrossedValue",
    "conditionType",
    "id",
    "queryId",
    "queryName",
  ],
  properties: {
    channelName: {
      type: "string",
    },
    conditionResultsChangedAddition: {
      type: "boolean",
    },
    conditionResultsChangedMinPct: {
      type: "integer",
    },
    conditionThresholdCrossedValue: {
      type: "integer",
    },
    conditionType: {
      $ref: "#/definitions/storedQuerySubscriptionConditionType",
    },
    id: {
      type: "integer",
    },
    queryId: {
      type: "integer",
    },
    queryName: {
      type: "string",
    },
  },
} as const;

export const storedQuerySubscriptionConditionTypeSchema = {
  type: "string",
  enum: [
    "controlStatusChanged",
    "historyPointAdded",
    "resultsChanged",
    "thresholdCrossed",
  ],
} as const;

export const storedQuerySubscriptionInputSchema = {
  type: "object",
  required: [
    "channelId",
    "conditionResultsChangedAddition",
    "conditionResultsChangedMinPct",
    "conditionThresholdCrossedValue",
    "conditionType",
    "queryId",
  ],
  properties: {
    channelId: {
      type: "integer",
    },
    conditionResultsChangedAddition: {
      type: "boolean",
    },
    conditionResultsChangedMinPct: {
      type: "integer",
    },
    conditionThresholdCrossedValue: {
      type: "integer",
    },
    conditionType: {
      $ref: "#/definitions/storedQuerySubscriptionConditionType",
    },
    queryId: {
      type: "integer",
    },
  },
} as const;

export const storedQuerySubscriptionsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/storedQuerySubscription",
  },
} as const;

export const stringObjectSchema = {
  type: "object",
  additionalProperties: {
    type: "string",
  },
} as const;

export const stringsSchema = {
  type: "array",
  items: {
    type: "string",
  },
} as const;

export const timeSchema = {
  type: "string",
  format: "time",
} as const;

export const traceSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/traceNodes",
  },
} as const;

export const traceNodeSchema = {
  required: ["entityId", "entityName", "entityTypeId", "sourceId"],
  properties: {
    entityId: {
      type: "string",
    },
    entityName: {
      type: "string",
    },
    entityTypeId: {
      type: "string",
    },
    sourceId: {
      type: "integer",
    },
  },
} as const;

export const traceNodesSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/traceNode",
  },
} as const;

export const traceQuerySchema = {
  type: "object",
  required: [
    "fromEntityId",
    "fromEntityTypeId",
    "fromSourceId",
    "toEntityId",
    "toEntityTypeId",
    "toSourceId",
  ],
  properties: {
    fromEntityId: {
      type: "string",
    },
    fromEntityTypeId: {
      type: "string",
    },
    fromSourceId: {
      type: "integer",
    },
    toEntityId: {
      type: "string",
    },
    toEntityTypeId: {
      type: "string",
    },
    toSourceId: {
      type: "integer",
    },
  },
} as const;

export const typeSchema = {
  type: "string",
  enum: ["boolean", "number", "string", "date", "dateTime", "time"],
} as const;

export const uniqueIntegersSchema = {
  type: "array",
  uniqueItems: true,
  items: {
    type: "integer",
  },
} as const;

export const updatePasswordBodySchema = {
  type: "object",
  required: ["newPassword", "oldPassword"],
  properties: {
    newPassword: {
      type: "string",
    },
    oldPassword: {
      type: "string",
    },
  },
} as const;

export const updateStoredQueryInputSchema = {
  type: "object",
  required: [
    "description",
    "highThreshold",
    "isControl",
    "name",
    "mediumThreshold",
    "shared",
  ],
  properties: {
    description: {
      type: "string",
    },
    highThreshold: {
      type: "integer",
    },
    isControl: {
      type: "boolean",
    },
    mediumThreshold: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    scopeID: {
      type: "integer",
      "x-nullable": true,
    },
    shared: {
      type: "boolean",
    },
  },
} as const;

export const usageLogSchema = {
  type: "object",
  required: ["timestamp", "url"],
  properties: {
    email: {
      $ref: "#/definitions/usageLogEmail",
    },
    timestamp: {
      $ref: "#/definitions/dateTime",
    },
    url: {
      type: "string",
    },
  },
} as const;

export const usageLogEmailSchema = {
  type: "string",
  "x-nullable": true,
} as const;

export const usageLogInputSchema = {
  type: "object",
  required: ["timestamp", "url"],
  properties: {
    timestamp: {
      $ref: "#/definitions/dateTime",
    },
    url: {
      type: "string",
    },
  },
} as const;

export const userAccountSchema = {
  type: "object",
  required: [
    "activated",
    "browseAccessSources",
    "email",
    "firstName",
    "importAccessSources",
    "ID",
    "lastName",
    "profiles",
    "role",
  ],
  properties: {
    ID: {
      type: "integer",
    },
    activated: {
      type: "boolean",
    },
    browseAccessSources: {
      $ref: "#/definitions/uniqueIntegers",
    },
    creationTs: {
      $ref: "#/definitions/optionalDateTime",
    },
    email: {
      type: "string",
    },
    firstName: {
      type: "string",
    },
    importAccessSources: {
      $ref: "#/definitions/uniqueIntegers",
    },
    inviteTs: {
      $ref: "#/definitions/optionalDateTime",
    },
    lastLoginTs: {
      $ref: "#/definitions/optionalDateTime",
    },
    lastName: {
      type: "string",
    },
    profiles: {
      $ref: "#/definitions/accessProfiles",
    },
    role: {
      $ref: "#/definitions/role",
    },
  },
} as const;

export const userAccountsSchema = {
  type: "array",
  items: {
    $ref: "#/definitions/userAccount",
  },
} as const;

export const valueSchema = {
  type: "object",
  required: ["type", "value"],
  properties: {
    type: {
      $ref: "#/definitions/type",
    },
    value: {
      type: "string",
    },
  },
} as const;

export const yAxisModeSchema = {
  type: "string",
  enum: ["optimal", "zeroToMax"],
} as const;
