// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client/index.js";
import { getAgentSourcesResponseTransformer } from "./transformers.gen.js";
import type {
  CreateSourceConnectorLogsData,
  CreateSourceConnectorLogsErrors,
  CreateSourceConnectorLogsResponses,
  GetAgentJsonStoredQueriesData,
  GetAgentJsonStoredQueriesErrors,
  GetAgentJsonStoredQueriesResponses,
  GetAgentScopesData,
  GetAgentScopesErrors,
  GetAgentScopesResponses,
  GetAgentSourcesData,
  GetAgentSourcesErrors,
  GetAgentSourcesResponses,
  ReloadSourceSnapshotData,
  ReloadSourceSnapshotErrors,
  ReloadSourceSnapshotResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry: HeyApiRegistry<Sdk> =
    new HeyApiRegistry<Sdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args?.key);
  }

  public getAgentScopes<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentScopesData, ThrowOnError>,
  ): RequestResult<
    GetAgentScopesResponses,
    GetAgentScopesErrors,
    ThrowOnError
  > {
    return (options?.client ?? this.client).get<
      GetAgentScopesResponses,
      GetAgentScopesErrors,
      ThrowOnError
    >({
      security: [
        {
          key: "apiToken",
          scheme: "basic",
          type: "http",
        },
      ],
      url: "/agent/scopes",
      ...options,
    });
  }

  public getAgentSources<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentSourcesData, ThrowOnError>,
  ): RequestResult<
    GetAgentSourcesResponses,
    GetAgentSourcesErrors,
    ThrowOnError
  > {
    return (options?.client ?? this.client).get<
      GetAgentSourcesResponses,
      GetAgentSourcesErrors,
      ThrowOnError
    >({
      responseTransformer: getAgentSourcesResponseTransformer,
      security: [
        {
          key: "apiToken",
          scheme: "basic",
          type: "http",
        },
      ],
      url: "/agent/sources",
      ...options,
    });
  }

  public getAgentJsonStoredQueries<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentJsonStoredQueriesData, ThrowOnError>,
  ): RequestResult<
    GetAgentJsonStoredQueriesResponses,
    GetAgentJsonStoredQueriesErrors,
    ThrowOnError
  > {
    return (options?.client ?? this.client).get<
      GetAgentJsonStoredQueriesResponses,
      GetAgentJsonStoredQueriesErrors,
      ThrowOnError
    >({
      security: [
        {
          key: "apiToken",
          scheme: "basic",
          type: "http",
        },
      ],
      url: "/agent/stored-queries;format=json",
      ...options,
    });
  }

  public createSourceConnectorLogs<ThrowOnError extends boolean = false>(
    options: Options<CreateSourceConnectorLogsData, ThrowOnError>,
  ): RequestResult<
    CreateSourceConnectorLogsResponses,
    CreateSourceConnectorLogsErrors,
    ThrowOnError
  > {
    return (options.client ?? this.client).post<
      CreateSourceConnectorLogsResponses,
      CreateSourceConnectorLogsErrors,
      ThrowOnError
    >({
      security: [
        {
          key: "source",
          scheme: "basic",
          type: "http",
        },
      ],
      url: "/sources/{id}/connector-logs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public reloadSourceSnapshot<ThrowOnError extends boolean = false>(
    options: Options<ReloadSourceSnapshotData, ThrowOnError>,
  ): RequestResult<
    ReloadSourceSnapshotResponses,
    ReloadSourceSnapshotErrors,
    ThrowOnError
  > {
    return (options.client ?? this.client).post<
      ReloadSourceSnapshotResponses,
      ReloadSourceSnapshotErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      security: [
        {
          key: "source",
          scheme: "basic",
          type: "http",
        },
        {
          key: "member",
          name: "Cookie",
          type: "apiKey",
        },
      ],
      url: "/sources/{id}/snapshots",
      ...options,
      headers: {
        "Content-Type": "application/octet-stream",
        ...options.headers,
      },
    });
  }
}
