// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  CreateSourceConnectorLogsData,
  CreateSourceConnectorLogsErrors,
  CreateSourceConnectorLogsResponses,
  GetAgentScopesData,
  GetAgentScopesErrors,
  GetAgentScopesResponses,
  GetAgentSourcesData,
  GetAgentSourcesErrors,
  GetAgentSourcesResponses,
  GetAgentStoredQueriesData,
  GetAgentStoredQueriesErrors,
  GetAgentStoredQueriesResponses,
  PerformAgentQueryData,
  PerformAgentQueryErrors,
  PerformAgentQueryResponses,
  ReloadSourceSnapshotData,
  ReloadSourceSnapshotErrors,
  ReloadSourceSnapshotResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args?.key);
  }

  public performAgentQuery<ThrowOnError extends boolean = false>(
    options: Options<PerformAgentQueryData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      PerformAgentQueryResponses,
      PerformAgentQueryErrors,
      ThrowOnError
    >({
      security: [{ scheme: "basic", type: "http" }],
      url: "/agent/query",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public getAgentScopes<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentScopesData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetAgentScopesResponses,
      GetAgentScopesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "basic", type: "http" }],
      url: "/agent/scopes",
      ...options,
    });
  }

  public getAgentSources<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentSourcesData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetAgentSourcesResponses,
      GetAgentSourcesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "basic", type: "http" }],
      url: "/agent/sources",
      ...options,
    });
  }

  public getAgentStoredQueries<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentStoredQueriesData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetAgentStoredQueriesResponses,
      GetAgentStoredQueriesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "basic", type: "http" }],
      url: "/agent/stored-queries",
      ...options,
    });
  }

  public createSourceConnectorLogs<ThrowOnError extends boolean = false>(
    options: Options<CreateSourceConnectorLogsData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      CreateSourceConnectorLogsResponses,
      CreateSourceConnectorLogsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "basic", type: "http" }],
      url: "/sources/{id}/connector-logs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public reloadSourceSnapshot<ThrowOnError extends boolean = false>(
    options: Options<ReloadSourceSnapshotData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      ReloadSourceSnapshotResponses,
      ReloadSourceSnapshotErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      security: [
        { scheme: "basic", type: "http" },
        { name: "Cookie", type: "apiKey" },
      ],
      url: "/sources/{id}/snapshots",
      ...options,
      headers: {
        "Content-Type": "application/octet-stream",
        ...options.headers,
      },
    });
  }
}
