// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import type { BaseHttpRequest } from "./core/BaseHttpRequest";
import type {
  CreateSourceConnectorLogsData,
  CreateSourceConnectorLogsResponse,
  ReloadSourceSnapshotData,
  ReloadSourceSnapshotResponse,
} from "./types.gen";

export class SourceService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * @param id
   * @param logs
   * @returns void The logs are created.
   * @throws ApiError
   */
  public createSourceConnectorLogs(
    id: CreateSourceConnectorLogsData["id"],
    logs: CreateSourceConnectorLogsData["logs"],
  ): CancelablePromise<CreateSourceConnectorLogsResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/sources/{id}/connector-logs",
      path: {
        id,
      },
      body: logs,
      errors: {
        401: "The requesting user is not authenticated.",
        403: "The requesting user is not authorized to perform this request.",
        404: "The specified resource is not found.",
        500: "The server experienced an error during the handling of the given request.",
      },
    });
  }

  /**
   * @param id
   * @param snapshot
   * @returns void The snapshot is accepted.
   * @throws ApiError
   */
  public reloadSourceSnapshot(
    id: ReloadSourceSnapshotData["id"],
    snapshot: ReloadSourceSnapshotData["snapshot"],
  ): CancelablePromise<ReloadSourceSnapshotResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/sources/{id}/snapshots",
      path: {
        id,
      },
      body: snapshot,
      errors: {
        401: "The requesting user is not authenticated.",
        403: "The requesting user is not authorized to perform this request.",
        404: "The specified resource is not found.",
        500: "The server experienced an error during the handling of the given request.",
      },
    });
  }
}
