// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetAgentSourcesResponse,
  PerformAgentQueryResponse,
} from "./types.gen.js";

const groupByQueryResultSchemaResponseTransformer = (data: any) => {
  data.subPages = groupByQueryResultsPageSchemaResponseTransformer(
    data.subPages,
  );
  return data;
};

const groupByQueryResultsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) =>
    groupByQueryResultSchemaResponseTransformer(item),
  );
  return data;
};

const groupByQueryResultsPageSchemaResponseTransformer = (data: any) => {
  data.results = groupByQueryResultsSchemaResponseTransformer(data.results);
  return data;
};

const groupByQueryResultsPagesSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) =>
    groupByQueryResultsPageSchemaResponseTransformer(item),
  );
  return data;
};

const dateTimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const removalRequestSchemaResponseTransformer = (data: any) => {
  data.requestedAt = dateTimeSchemaResponseTransformer(data.requestedAt);
  return data;
};

const removalRequestsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => removalRequestSchemaResponseTransformer(item));
  return data;
};

const queryResultSchemaResponseTransformer = (data: any) => {
  data.linkGroupByPages = groupByQueryResultsPagesSchemaResponseTransformer(
    data.linkGroupByPages,
  );
  data.linkPages = queryResultsPagesSchemaResponseTransformer(data.linkPages);
  data.removalRequests = removalRequestsSchemaResponseTransformer(
    data.removalRequests,
  );
  return data;
};

const queryResultsSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => queryResultSchemaResponseTransformer(item));
  return data;
};

const queryResultsPageSchemaResponseTransformer = (data: any) => {
  data.results = queryResultsSchemaResponseTransformer(data.results);
  return data;
};

const queryResultsPagesSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) =>
    queryResultsPageSchemaResponseTransformer(item),
  );
  return data;
};

export const performAgentQueryResponseTransformer = async (
  data: any,
): Promise<PerformAgentQueryResponse> => {
  data = queryResultsPagesSchemaResponseTransformer(data);
  return data;
};

const optionalDateTimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const sourceSchemaResponseTransformer = (data: any) => {
  if (data.lastReloadTimestamp) {
    data.lastReloadTimestamp = optionalDateTimeSchemaResponseTransformer(
      data.lastReloadTimestamp,
    );
  }
  return data;
};

const sourcesSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => sourceSchemaResponseTransformer(item));
  return data;
};

export const getAgentSourcesResponseTransformer = async (
  data: any,
): Promise<GetAgentSourcesResponse> => {
  data = sourcesSchemaResponseTransformer(data);
  return data;
};
