// This file is auto-generated by @hey-api/openapi-ts

import type { GetAgentSourcesResponse } from "./types.gen.js";

const optionalDateTimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const sourceSchemaResponseTransformer = (data: any) => {
  if (data.lastReloadTimestamp) {
    data.lastReloadTimestamp = optionalDateTimeSchemaResponseTransformer(
      data.lastReloadTimestamp,
    );
  }
  return data;
};

const sourcesSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => sourceSchemaResponseTransformer(item));
  return data;
};

export const getAgentSourcesResponseTransformer = async (
  data: any,
): Promise<GetAgentSourcesResponse> => {
  data = sourcesSchemaResponseTransformer(data);
  return data;
};
