// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {});
};

export type DateTime = Date;

export type Snapshot = Blob | File;

export type ConnectorLogLevel = "info" | "alert";

export type ConnectorLog = {
  level: ConnectorLogLevel;
  message: string;
  timestamp: DateTime;
};

export type ConnectorLogs = Array<ConnectorLog>;

export type CreateSourceConnectorLogsData = {
  body: ConnectorLogs;
  path: {
    id: number;
  };
  query?: never;
  url: "/sources/{id}/connector-logs";
};

export type CreateSourceConnectorLogsErrors = {
  /**
   * The requesting user is not authenticated.
   */
  401: unknown;
  /**
   * The requesting user is not authorized to perform this request.
   */
  403: unknown;
  /**
   * The specified resource is not found.
   */
  404: unknown;
  /**
   * The server experienced an error during the handling of the given request.
   */
  500: unknown;
};

export type CreateSourceConnectorLogsResponses = {
  /**
   * The logs are created.
   */
  204: unknown;
};

export type ReloadSourceSnapshotData = {
  body: Snapshot;
  path: {
    id: number;
  };
  query?: never;
  url: "/sources/{id}/snapshots";
};

export type ReloadSourceSnapshotErrors = {
  /**
   * The requesting user is not authenticated.
   */
  401: unknown;
  /**
   * The requesting user is not authorized to perform this request.
   */
  403: unknown;
  /**
   * The specified resource is not found.
   */
  404: unknown;
  /**
   * The server experienced an error during the handling of the given request.
   */
  500: unknown;
};

export type ReloadSourceSnapshotResponses = {
  /**
   * The snapshot is accepted.
   */
  204: unknown;
};
