// This file is auto-generated by @hey-api/openapi-ts

export type ConnectorLog = {
  level: ConnectorLogLevel;
  message: string;
  timestamp: DateTime;
};

export type ConnectorLogLevel = "info" | "alert";

export type ConnectorLogs = Array<ConnectorLog>;

export type DateTime = Date;

export type Snapshot = Blob | File;

export type CreateSourceConnectorLogsData = {
  id: number;
  logs: ConnectorLogs;
};

export type CreateSourceConnectorLogsResponse = void;

export type ReloadSourceSnapshotData = {
  id: number;
  snapshot: Snapshot;
};

export type ReloadSourceSnapshotResponse = void;
